name: promote

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
        
     - uses: actions/checkout@v2
     - uses: akhileshns/heroku-deploy@v3.12.12
       with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_NOA}}
          heroku_app_name: "noa-production"
          heroku_email: "noa.kfir@aquant.io"
          branch: master
          justlogin: true
          dontuseforce: true
          buildpack: true
          appdir: app
     - run: API_URL=https://my.new.dev.api.com heroku pipelines:promote -a noa-production --to wrong-app1
